[project]
name = "whitepaper-to-socials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
    "reportlab>=4.4.2",
]
